services:
  stun_server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: stun_server
    networks:
      - public
    ports:
      - "8090:8090"
    environment:
      - CKB_CHAIN=dev
      - API_URL=http://127.0.0.1:8114
    command: [ "run" ]

  nat1_gateway:
    image: alpine:latest
    container_name: nat1_gateway
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - nat1
      - public
    command: >
      sh -c "
        apk add --no-cache iptables ip6tables tcpdump &&
        # Assume eth0 is nat1 and eth1 is public
        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT &&
        iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
        ip6tables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        ip6tables -A FORWARD -i eth0 -o eth1 -j ACCEPT &&
        ip6tables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
        tail -f /dev/null
      "
    depends_on:
      - stun_server

  peer1:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: peer1
    cap_add:
      - NET_ADMIN
    networks:
      - nat1
    depends_on:
      - nat1_gateway
    environment:
      - CKB_CHAIN=dev
      - API_URL=http://127.0.0.1:8114
    command: [ "run" ]

  nat2_gateway:
    image: alpine:latest
    container_name: nat2_gateway
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - nat2
      - public
    command: >
      sh -c "
        apk add --no-cache iptables ip6tables tcpdump &&
        # Assume eth0 is nat2 and eth1 is public
        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT &&
        iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
        ip6tables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        ip6tables -A FORWARD -i eth0 -o eth1 -j ACCEPT &&
        ip6tables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
        tail -f /dev/null
      "
    depends_on:
      - stun_server

  peer2:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: peer2
    cap_add:
      - NET_ADMIN
    networks:
      - nat2
    depends_on:
      - nat2_gateway
    environment:
      - CKB_CHAIN=dev
      - API_URL=http://127.0.0.1:8114
    command: [ "run" ]

networks:
  nat1:
    driver: bridge
    enable_ipv6: true
  nat2:
    driver: bridge
    enable_ipv6: true
  public:
    driver: bridge
    enable_ipv6: true
